### ISSUE TITLE
Adding RStudio Addins?

### ISSUE THREAD

**Issue by jjchern** [decisionpatterns/backpipe#2]
So that it'd be easier to bind a keyboard shortcut?

**Comment by ctbrown** [comment]
It is possible and quite easy to create an rstudio addin, but I am not sure
how the bind a keyboard shortcut works.  Do you know?  Can you supply a
link?  And what keyboard shortcut makes sense? CTRL+SHIFT+?  ?

**Comment by jjchern** [comment]
In RStudio, `Command/Ctrl + Shift + M` gives the `%>%`, so two candidates are:

- `Command/Ctrl + Shift + N` for `%<%`, as "N" is on the left of "M", but this shortcut has been taken, or
- `Command/Ctrl + Shift + <` for `%<%`, as "<" is quite natural for the backward pipe, but it's also been taken.

How about `Command/Ctrl + Option/Alt + M`?

**Comment by ctbrown** [comment]
Fixed in v0.2.0 headed to CRAN.
